### ISSUE TITLE
Error With PSD Constraint

### ISSUE THREAD

**Issue by chelseas** [jump-dev/MosekTools.jl#100] opened 2022-04-22 17:14 UTC
I am using MOSEK through JuMP like:
```julia
model = Model(optimizer_with_attributes(Mosek.Optimizer, "QUIET" => false))
```
but when I try to apply a PSD constraint to a new variable in my model like:
```julia
M_var = @variable(model, M[1:mn_dim, 1:mn_dim], PSD)
```
or
```julia
M_var = @variable(model, M[1:mn_dim, 1:mn_dim] in PSDCone())
```
I get this error on solve:
```
ERROR: LoadError: Cannot add MathOptInterface.GreaterThan{Float64} constraint on a matrix variable
```

Note: I am trying to do mixed-integer semi-definite programming so I do already have binary variables in my model.

**Comment by odow** [comment] 2022-04-22 21:19
Please provide a reproducible example.

**Comment by blegat** [comment] 2022-04-23 13:54
Mosek does not support bounds on entries of PSD variable. So this won't work with Mosek:
```julia
@variable(model, M[1:n, 1:n], PSD, lower_bound = 0.0)
```
This won't work either:
```julia
@variable(model, M[1:n, 1:n], PSD)
@constraint(model, M[1, 1] in MOI.GreatherThan(0.0))
```
But this should work
```julia
@variable(model, M[1:n, 1:n], PSD)
@constraint(model, M[1, 1] >= 0.0)
```
See also https://github.com/jump-dev/MosekTools.jl/issues/48

**Comment by odow** [comment] 2022-08-18 05:39
Closing because this seems like it is working as expected. The solution is to add a linear constraint, not a variable bound.

**Closed by odow** 2022-08-18 05:39 UTC
