### ISSUE TITLE
Excessive pre-factor nonzeros in sdplib instance

### ISSUE THREAD

**Issue by nrontsis** [jump-dev/MosekTools.jl#40] opened 2019-08-16 15:09 UTC
# The issue
Solving `gpp124-1` from `sdplib` via `JuMP` and `Mosek` results in an inefficient (fully dense?) formulation.

# Code used
Download [gpp124-1.jld2](https://github.com/mariohsouto/ProxSDP.jl/files/3509515/gpp124-1.jld2.zip) and run
```julia
using LinearAlgebra, SparseArrays
using MosekTools, JuMP
using JLD2

function solve_sdpa_jump(c, F; solver=Mosek.Optimizer, kwargs...)
    model = Model(with_optimizer(solver; kwargs...))
    #= Solve the following optimization problem

    minimize c'x
    subject to  F1*x1 + ... + Fm*xm - F0 ⪰ 0

    See https://freesoft.dev/program/129366650
    =#
    m = length(c); n = size(F[1], 1)
    @variable(model, x[1:m])

    A = hcat([F[i+1][:] for i = 1:m]...)
    b = -Vector(F[1][:])
    @constraint(model, A*x + b in MOI.PositiveSemidefiniteConeSquare(n))

    @objective(model, Min, dot(c, x))

    JuMP.optimize!(model)
    @show JuMP.termination_status(model)
    return value.(x), JuMP.objective_value(model)
end

@load "gpp124-1.jld2" c F
solution, solution_objective = solve_sdpa_jump(c, F, solver=Mosek.Optimizer)
```
In the example above Mosek reports
```
Factor     - nonzeros before factor : 3.00e+07
```
which is in the same order as  `length(A) + length(F[1]) = 1922000 + 125^2` where `A` is defined in `solve_sdpa_jump` above.
I would expect a number of nonzeros in the order of  ```nnz(A) + length(F[1]) = 15500 + 125^2```.

Is this behaviour expected?

On a related note solving the dual of `gpp124-1` via: 
```julia
function solve_sdpa_jump_dual(c, F; solver=Mosek.Optimizer, kwargs...)
    model = Model(with_optimizer(solver; kwargs...))
    m = length(c); n = size(F[1], 1)
    @variable(model, Y[1:n, 1:n], PSD)
    for i = 1:m
        @constraint(model, dot(Y, F[i + 1]) == c[i])
    end
    @objective(model, Max, dot(F[1], Y))

    JuMP.optimize!(model)
    @show JuMP.termination_status(model)
    return value.(Y), JuMP.objective_value(model)
end
```
does not exhibit the same problem.

**Comment by odow** [comment] 2022-08-18 05:44
Closing because this is expected. We have to reformulate the problem into something Mosek supports, which adds new variables and constraints. 

You can use Dualization.jl to solve the dual, which results in a better formulation:
https://github.com/jump-dev/Dualization.jl

```Julia
using JuMP, Dualization, MosekTools
model = Model(dual_optimizer(Mosek.Optimizer))
```

**Closed by odow** 2022-08-18 05:44 UTC

**Comment by nrontsis** [comment] 2022-08-25 08:26
I would appreciate it if you could elaborate why this is expected behaviour. In my mind we seem to be unnecessarily loosing sparsity, but perhaps I am missing something?

Solving the dual was the approach I followed back then, but it surprised me that the stats of the primal.

**Comment by odow** [comment] 2022-08-25 08:44
The problem is that we can't solve the primal as formulated:
```
minimize c'x
subject to  F1*x1 + ... + Fm*xm - F0 ⪰ 0
```
because you have a `VectorAffineFunction-in-PositiveSemidefiniteConeSquare` constraint, but Mosek only supports `VectorOfVariables-in-PositiveSemidefiniteConeTriangle`, so JuMP reformulates the problem by adding additional slack variables and new equality constraints.

The dual formulation doesn't need this reformulation.
