### ISSUE TITLE
Zero ConstraintPrimal and ConstraintDual for SDP constraint

### ISSUE THREAD

**Issue by blegat** [jump-dev/MosekTools.jl#14] opened 2019-02-28 15:26 UTC
I cannot reproduce it locally, similar to https://github.com/JuliaOpt/MosekTools.jl/issues/1
See https://travis-ci.org/JuliaOpt/MosekTools.jl/jobs/499327096#L512-L700

**Comment by blegat** [comment] 2020-02-04 10:56
@ulfworsoe Could you take a look at this ? It would be helpful to have Travis tests passing.

**Comment by ulfworsoe** [comment] 2020-02-14 15:11
I'll have a look. I suspect it is probably caused by the tests using solve.mosek.com instead of a local server.

**Comment by ulfworsoe** [comment] 2020-02-17 11:20
I can confirm that it is an underlying problem related to communication with the opt-server. It has to be fixed in Mosek, and I don't know when I'll have a fix ready. I'll close the ticket when it works.

**Comment by blegat** [comment] 2020-10-04 09:52
@ulfworsoe Thanks, CI is passing now, this seems to have been fixed!

**Comment by ulfworsoe** [comment] 2022-02-10 10:35
I can't close issues, but https://github.com/jump-dev/MosekTools.jl/pull/86 should update tests so all use the optserver,

**Comment by odow** [comment] 2022-08-18 05:45
Closing because this issues seems to be fixed.

**Closed by odow** 2022-08-18 05:45 UTC
